### ISSUE TITLE
Download data in different formats

### ISSUE THREAD

**Issue by hlydecker** [Weed-AI/Weed-AI#675]
It might be very useful to allow users to download data directly into an ML ready format such as YOLO. 

I could probably repurpose some of the dataset utilities I developed for camera traps to do this, because we turn a COCO like dataset into YOLO.

YOLO requires:
a dataset.yaml with:
```yaml
path: weed_ai_dataset
train: train/images
val: val/images
test: test/images

nc: 2
names: ['Weed: Lolium rigidum','Weed: Sonchus oleraceus']
```

Where path directs to where the images are stored relative to the YOLO model install.

Individual annotations are stored for each image in text files with the same name as the image, but with the .txt extension. These are in the "labels" directory that sits adjacent to the relevant "images" directory.

These are space separated text files, with:
 <class_id> <x_center> <y_center> <width> <height>
```
0 0.25 0.1 0.43 0.3
```

Note that x,y,w,h are all in relative percentage of the image.

This is not for us to deal with now, but would be useful in the future!
